export default interface Particle {
    compareTo(arg0: any): number;
    compareTo(arg0: any): number;
    getDataType(): any;
    getDeclaringClass(): any;
    name(): string;
    ordinal(): number;
}
export default class Particle {
    static get $javaClass(): any;
    static get ASH(): Particle;
    static get BARRIER(): Particle;
    static get BLOCK_CRACK(): Particle;
    static get BLOCK_DUST(): Particle;
    static get BUBBLE_COLUMN_UP(): Particle;
    static get BUBBLE_POP(): Particle;
    static get CAMPFIRE_COSY_SMOKE(): Particle;
    static get CAMPFIRE_SIGNAL_SMOKE(): Particle;
    static get CLOUD(): Particle;
    static get COMPOSTER(): Particle;
    static get CRIMSON_SPORE(): Particle;
    static get CRIT(): Particle;
    static get CRIT_MAGIC(): Particle;
    static get CURRENT_DOWN(): Particle;
    static get DAMAGE_INDICATOR(): Particle;
    static get DOLPHIN(): Particle;
    static get DRAGON_BREATH(): Particle;
    static get DRIPPING_HONEY(): Particle;
    static get DRIPPING_OBSIDIAN_TEAR(): Particle;
    static get DRIP_LAVA(): Particle;
    static get DRIP_WATER(): Particle;
    static get ENCHANTMENT_TABLE(): Particle;
    static get END_ROD(): Particle;
    static get EXPLOSION_HUGE(): Particle;
    static get EXPLOSION_LARGE(): Particle;
    static get EXPLOSION_NORMAL(): Particle;
    static get FALLING_DUST(): Particle;
    static get FALLING_HONEY(): Particle;
    static get FALLING_LAVA(): Particle;
    static get FALLING_NECTAR(): Particle;
    static get FALLING_OBSIDIAN_TEAR(): Particle;
    static get FALLING_WATER(): Particle;
    static get FIREWORKS_SPARK(): Particle;
    static get FLAME(): Particle;
    static get FLASH(): Particle;
    static get HEART(): Particle;
    static get ITEM_CRACK(): Particle;
    static get LANDING_HONEY(): Particle;
    static get LANDING_LAVA(): Particle;
    static get LANDING_OBSIDIAN_TEAR(): Particle;
    static get LAVA(): Particle;
    static get LEGACY_BLOCK_CRACK(): Particle;
    static get LEGACY_BLOCK_DUST(): Particle;
    static get LEGACY_FALLING_DUST(): Particle;
    static get MOB_APPEARANCE(): Particle;
    static get NAUTILUS(): Particle;
    static get NOTE(): Particle;
    static get PORTAL(): Particle;
    static get REDSTONE(): Particle;
    static get REVERSE_PORTAL(): Particle;
    static get SLIME(): Particle;
    static get SMOKE_LARGE(): Particle;
    static get SMOKE_NORMAL(): Particle;
    static get SNEEZE(): Particle;
    static get SNOWBALL(): Particle;
    static get SNOW_SHOVEL(): Particle;
    static get SOUL(): Particle;
    static get SOUL_FIRE_FLAME(): Particle;
    static get SPELL(): Particle;
    static get SPELL_INSTANT(): Particle;
    static get SPELL_MOB(): Particle;
    static get SPELL_MOB_AMBIENT(): Particle;
    static get SPELL_WITCH(): Particle;
    static get SPIT(): Particle;
    static get SQUID_INK(): Particle;
    static get SUSPENDED(): Particle;
    static get SUSPENDED_DEPTH(): Particle;
    static get SWEEP_ATTACK(): Particle;
    static get TOTEM(): Particle;
    static get TOWN_AURA(): Particle;
    static get VILLAGER_ANGRY(): Particle;
    static get VILLAGER_HAPPY(): Particle;
    static get WARPED_SPORE(): Particle;
    static get WATER_BUBBLE(): Particle;
    static get WATER_DROP(): Particle;
    static get WATER_SPLASH(): Particle;
    static get WATER_WAKE(): Particle;
    static get WHITE_ASH(): Particle;
}
