import Blob from './Blob.js';
import CallableStatement from './CallableStatement.js';
import Clob from './Clob.js';
import DatabaseMetaData from './DatabaseMetaData.js';
import NClob from './NClob.js';
import PreparedStatement from './PreparedStatement.js';
import SQLWarning from './SQLWarning.js';
import SQLXML from './SQLXML.js';
import Savepoint from './Savepoint.js';
import Statement from './Statement.js';
import Struct from './Struct.js';
import Wrapper from './Wrapper.js';
import _Array from './Array.js';
export default interface Connection extends Wrapper {
    abort(arg0: any): void;
    clearWarnings(): void;
    close(): void;
    commit(): void;
    createArrayOf(arg0: string, arg1: Array<any>): _Array;
    createBlob(): Blob;
    createClob(): Clob;
    createNClob(): NClob;
    createSQLXML(): SQLXML;
    createStatement(): Statement;
    createStatement(arg0: number, arg1: number): Statement;
    createStatement(arg0: number, arg1: number, arg2: number): Statement;
    createStruct(arg0: string, arg1: Array<any>): Struct;
    getAutoCommit(): boolean;
    getCatalog(): string;
    getClientInfo(): any;
    getClientInfo(arg0: string): string;
    getHoldability(): number;
    getMetaData(): DatabaseMetaData;
    getNetworkTimeout(): number;
    getSchema(): string;
    getTransactionIsolation(): number;
    getTypeMap(): any;
    getWarnings(): SQLWarning;
    isClosed(): boolean;
    isReadOnly(): boolean;
    isValid(arg0: number): boolean;
    isWrapperFor(arg0: any): boolean;
    nativeSQL(arg0: string): string;
    prepareCall(arg0: string): CallableStatement;
    prepareCall(arg0: string, arg1: number, arg2: number): CallableStatement;
    prepareCall(arg0: string, arg1: number, arg2: number, arg3: number): CallableStatement;
    prepareStatement(arg0: string): PreparedStatement;
    prepareStatement(arg0: string, arg1: Array<string>): PreparedStatement;
    prepareStatement(arg0: string, arg1: number): PreparedStatement;
    prepareStatement(arg0: string, arg1: Array<number>): PreparedStatement;
    prepareStatement(arg0: string, arg1: number, arg2: number): PreparedStatement;
    prepareStatement(arg0: string, arg1: number, arg2: number, arg3: number): PreparedStatement;
    releaseSavepoint(arg0: Savepoint): void;
    rollback(): void;
    rollback(arg0: Savepoint): void;
    setAutoCommit(arg0: boolean): void;
    setCatalog(arg0: string): void;
    setClientInfo(arg0: any): void;
    setClientInfo(arg0: string, arg1: string): void;
    setHoldability(arg0: number): void;
    setNetworkTimeout(arg0: any, arg1: number): void;
    setReadOnly(arg0: boolean): void;
    setSavepoint(): Savepoint;
    setSavepoint(arg0: string): Savepoint;
    setSchema(arg0: string): void;
    setTransactionIsolation(arg0: number): void;
    setTypeMap(arg0: any): void;
    unwrap(arg0: any): any;
}
export default class Connection {
    static get $javaClass(): any;
    static get TRANSACTION_NONE(): number;
    static get TRANSACTION_READ_COMMITTED(): number;
    static get TRANSACTION_READ_UNCOMMITTED(): number;
    static get TRANSACTION_REPEATABLE_READ(): number;
    static get TRANSACTION_SERIALIZABLE(): number;
}
