import ObjectOutput from './ObjectOutput.js';
import ObjectOutputStream$PutField from './ObjectOutputStream$PutField.js';
import ObjectStreamConstants from './ObjectStreamConstants.js';
import OutputStream from './OutputStream.js';
import SerializablePermission from './SerializablePermission.js';
export default interface ObjectOutputStream extends OutputStream, ObjectOutput, ObjectStreamConstants {
    close(): void;
    defaultWriteObject(): void;
    flush(): void;
    putFields(): ObjectOutputStream$PutField;
    reset(): void;
    useProtocolVersion(arg0: number): void;
    write(arg0: number): void;
    write(arg0: Array<number>): void;
    write(arg0: Array<number>, arg1: number, arg2: number): void;
    writeBoolean(arg0: boolean): void;
    writeByte(arg0: number): void;
    writeBytes(arg0: string): void;
    writeChar(arg0: number): void;
    writeChars(arg0: string): void;
    writeDouble(arg0: number): void;
    writeFields(): void;
    writeFloat(arg0: number): void;
    writeInt(arg0: number): void;
    writeLong(arg0: number): void;
    writeObject(arg0: any): void;
    writeShort(arg0: number): void;
    writeUTF(arg0: string): void;
    writeUnshared(arg0: any): void;
}
export default class ObjectOutputStream {
    static get $javaClass(): any;
    constructor(arg0: OutputStream);
    static get PROTOCOL_VERSION_1(): number;
    static get PROTOCOL_VERSION_2(): number;
    static get SC_BLOCK_DATA(): number;
    static get SC_ENUM(): number;
    static get SC_EXTERNALIZABLE(): number;
    static get SC_SERIALIZABLE(): number;
    static get SC_WRITE_METHOD(): number;
    static get STREAM_MAGIC(): number;
    static get STREAM_VERSION(): number;
    static get SUBCLASS_IMPLEMENTATION_PERMISSION(): SerializablePermission;
    static get SUBSTITUTION_PERMISSION(): SerializablePermission;
    static get TC_ARRAY(): number;
    static get TC_BASE(): number;
    static get TC_BLOCKDATA(): number;
    static get TC_BLOCKDATALONG(): number;
    static get TC_CLASS(): number;
    static get TC_CLASSDESC(): number;
    static get TC_ENDBLOCKDATA(): number;
    static get TC_ENUM(): number;
    static get TC_EXCEPTION(): number;
    static get TC_LONGSTRING(): number;
    static get TC_MAX(): number;
    static get TC_NULL(): number;
    static get TC_OBJECT(): number;
    static get TC_PROXYCLASSDESC(): number;
    static get TC_REFERENCE(): number;
    static get TC_RESET(): number;
    static get TC_STRING(): number;
    static get baseWireHandle(): number;
}
